INSERT IGNORE INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `metadata`, `desc`, `weight`) VALUES
('aligatormeat', 'Alligator Meat', 200, 1, 'item_standard', 1, '{}', 'Fresh meat carved from a freshly hunted alligator', 0.1),
('aligatorto', 'Alligator Tooth', 200, 1, 'item_standard', 0, '{}', 'Sharp tooth pulled from a freshly hunted alligator', 0.1),
('aligatorpelt', 'Alligator Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw alligator pelt, fresh from skinning, not yet tanned', 0.1),
('meat', 'Meat', 200, 1, 'item_standard', 1, '{}', 'Raw meat harvested from a freshly hunted animal', 0.1),
('armadillos', 'Armadillo Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw armadillo pelt, fresh from skinning, not yet tanned', 0.1),
('badgers', 'Badger Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw badger pelt, fresh from skinning, not yet tanned', 0.1),
('biggame', 'Big Game Meat', 200, 1, 'item_standard', 1, '{}', 'Fresh meat carved from freshly hunted big game', 0.1),
('bearg', 'Bear Claw', 200, 1, 'item_standard', 0, '{}', 'Sharp claw taken from a freshly hunted bear', 0.1),
('bbears', 'Bear Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw bear pelt, fresh from skinning, not yet tanned', 0.1),
('bearc', 'Black Bear Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw black bear pelt, fresh from skinning, not yet tanned', 0.1),
('scentg', 'Scent Gland', 200, 1, 'item_standard', 0, '{}', 'Scent gland harvested from a freshly hunted animal, used for lures', 0.1),
('beawers', 'Beaver Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw beaver pelt, fresh from skinning, not yet tanned', 0.1),
('mutton', 'Mutton', 200, 1, 'item_standard', 1, '{}', 'Fresh meat carved from a freshly hunted sheep or goat', 0.1),
('ramhorn', 'Ram Horn', 200, 1, 'item_standard', 0, '{}', 'Horn taken from a freshly hunted ram', 0.1),
('rams', 'Ram Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw ram pelt, fresh from skinning, not yet tanned', 0.1),
('pork', 'Pork', 200, 1, 'item_standard', 1, '{}', 'Fresh meat carved from a freshly hunted pig or boar', 0.1),
('boarmusk', 'Boar Tusk', 200, 1, 'item_standard', 0, '{}', 'Tusk taken from a freshly hunted boar', 0.1),
('porkfat', 'Pork Fat', 200, 1, 'item_standard', 0, '{}', 'Rendered fat harvested from a freshly hunted pig or boar', 0.1),
('jabapelt', 'Boar Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw boar pelt, fresh from skinning, not yet tanned', 0.1),
('buckantler', 'Buck Antler', 200, 1, 'item_standard', 0, '{}', 'Antler taken from a freshly hunted buck', 0.1),
('deerskin', 'Deer Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw deer pelt, fresh from skinning, not yet tanned', 0.1),
('deerheart', 'Deer Heart', 200, 1, 'item_standard', 0, '{}', 'Heart harvested from a freshly hunted deer', 0.1),
('beef', 'Beef', 200, 1, 'item_standard', 1, '{}', 'Fresh meat carved from a freshly hunted cow or bull', 0.1),
('bisonhorn', 'Bison Horn', 200, 1, 'item_standard', 0, '{}', 'Horn taken from a freshly hunted bison', 0.1),
('bisons', 'Bison Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw bison pelt, fresh from skinning, not yet tanned', 0.1),
('bullhorn', 'Bull Horn', 200, 1, 'item_standard', 0, '{}', 'Horn taken from a freshly hunted bull', 0.1),
('bulls', 'Bull Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw bull pelt, fresh from skinning, not yet tanned', 0.1),
('cougars', 'Cougar Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw cougar pelt, fresh from skinning, not yet tanned', 0.1),
('cows', 'Cow Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw cow pelt, fresh from skinning, not yet tanned', 0.1),
('coyotes', 'Coyote Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw coyote pelt, fresh from skinning, not yet tanned', 0.1),
('provision_meat_crustacean', 'Crab Meat', 200, 1, 'item_standard', 1, '{}', 'Fresh meat picked from a freshly caught crab or crawfish', 0.1),
('elkantler', 'Elk Antler', 200, 1, 'item_standard', 0, '{}', 'Antler taken from a freshly hunted elk', 0.1),
('elks', 'Elk Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw elk pelt, fresh from skinning, not yet tanned', 0.1),
('foxskin', 'Fox Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw fox pelt, fresh from skinning, not yet tanned', 0.1),
('provision_meat_herptile', 'Reptile Meat', 200, 1, 'item_standard', 1, '{}', 'Fresh meat carved from a freshly hunted reptile', 0.1),
('lizards', 'Lizard Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw lizard pelt, fresh from skinning, not yet tanned', 0.1),
('goats', 'Goat Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw goat pelt, fresh from skinning, not yet tanned', 0.1),
('pecaris', 'Peccary Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw peccary pelt, fresh from skinning, not yet tanned', 0.1),
('mooseantler', 'Moose Antler', 200, 1, 'item_standard', 0, '{}', 'Antler taken from a freshly hunted moose', 0.1),
('mooses', 'Moose Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw moose pelt, fresh from skinning, not yet tanned', 0.1),
('oxhorn', 'Ox Horn', 200, 1, 'item_standard', 0, '{}', 'Horn taken from a freshly hunted ox', 0.1),
('oxs', 'Ox Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw ox pelt, fresh from skinning, not yet tanned', 0.1),
('panthers', 'Panther Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw panther pelt, fresh from skinning, not yet tanned', 0.1),
('wool', 'Wool', 200, 1, 'item_standard', 0, '{}', 'Raw wool sheared from a freshly hunted sheep', 0.1),
('pigpelt', 'Pig Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw pig pelt, fresh from skinning, not yet tanned', 0.1),
('opossums', 'Opossum Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw opossum pelt, fresh from skinning, not yet tanned', 0.1),
('pronghornh', 'Pronghorn Horn', 200, 1, 'item_standard', 0, '{}', 'Horn taken from a freshly hunted pronghorn', 0.1),
('prongs', 'Pronghorn Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw pronghorn pelt, fresh from skinning, not yet tanned', 0.1),
('meatconejo', 'Rabbit Meat', 200, 1, 'item_standard', 1, '{}', 'Fresh meat carved from a freshly hunted rabbit', 0.1),
('rabbits', 'Rabbit Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw rabbit pelt, fresh from skinning, not yet tanned', 0.1),
('rabbitpaw', 'Rabbit Paw', 200, 1, 'item_standard', 0, '{}', 'Paw taken from a freshly hunted rabbit, said to bring luck', 0.1),
('raccoons', 'Raccoon Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw raccoon pelt, fresh from skinning, not yet tanned', 0.1),
('resource_pelt_skunk', 'Skunk Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw skunk pelt, fresh from skinning, not yet tanned', 0.1),
('turtleshell', 'Turtle Shell', 200, 1, 'item_standard', 0, '{}', 'Shell taken from a freshly hunted turtle', 0.1),
('wolfheart', 'Wolf Heart', 200, 1, 'item_standard', 0, '{}', 'Heart harvested from a freshly hunted wolf', 0.1),
('wolfpelt', 'Wolf Pelt', 200, 1, 'item_standard', 0, '{}', 'Raw wolf pelt, fresh from skinning, not yet tanned', 0.1),
('bird', 'Bird Meat', 200, 1, 'item_standard', 1, '{}', 'Fresh meat carved from a freshly hunted bird', 0.1),
('feathers', 'Feathers', 200, 1, 'item_standard', 0, '{}', 'Feathers plucked from a freshly hunted bird', 0.1),
('resource_skin_lizard', 'Snake Skin', 200, 1, 'item_standard', 0, '{}', 'Raw snake skin, fresh from skinning, not yet tanned', 0.1),
('snake_poison', 'Snake Venom', 200, 1, 'item_standard', 0, '{}', 'Venom extracted from a freshly hunted snake', 0.1);